name: pyposeidon

channels:
  - conda-forge
  - gbrey

dependencies:
  - python=3.8
  - pyposeidon=0.6.0
  - pschism
  - delft3d4
  - xorg-libxcursor
  - xorg-libxft
  - xorg-libxinerama
  - xorg-libxcb
  - fltk
  - nodejs
  - ipympl
  - pyviz_comms
  - jupyterlab<3
  - ipyevents=0.9.0
  - xvfbwrapper
  - geoviews >=1.9.4
