name: pyposeidon

channels:
  - conda-forge
  - gbrey

dependencies:
  - python=3.8
  - pyposeidon=0.5.2
  - pschism
  - delft3d4
  - xorg-libxcursor
  - xorg-libxft
  - xorg-libxinerama
  - fltk
  - nodejs
  - ipympl
  - pyviz_comms
  - pip
  - pip:
    - gmsh
    - "--editable=git+https://github.com/pydap/pydap.git@3f6aa190c59e3bbc6c834377a61579b20275ff69#egg=Pydap"
